force-app/main/default/objects/Food__c/Food__c.object-meta.xml
<CustomObject>
    <label>Food</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Food Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Foods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Food__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FoodtrgHandler.cls
public with sharing class FoodtrgHandler {
     //
    public static void calcPriceBurger(List<Food__c> lstofzc){
         for(Food__c a : lstofzc) {
         	a.Total_Price__c = a.Quantity__c * a.Price__c;
    	}
    }
    public static void calcPricePizza(List<Food__c> lstofzc){
         for(Food__c a : lstofzc) {
         	a.Total_Price__c = (a.Quantity__c * a.Price__c)*2;
    	}
    }
    public static void calcPriceChips(List<Food__c> lstofzc){
         for(Food__c a : lstofzc) {
         	a.Total_Price__c = (a.Quantity__c * a.Price__c)*4;
    	} 
    }
}