force-app/main/default/objects/Food__c/Food__c.object-meta.xml
<CustomObject>
    <label>Food</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Food Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Foods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food__c/fields/Lunch__c.field-meta.xml
<CustomField>
    <fullName>Lunch__c</fullName>
    <label>Lunch</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Burger</fullName>
            </value>
            <value>
                <fullName>Kebab</fullName>
            </value>
            <value>
                <fullName>Chips</fullName>
            </value>
            <value>
                <fullName>Pizza</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Food__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Food__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <label>Total Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FoodTest.cls
@isTest
private class FoodTest {

    @isTest
    static void burgerTest() {
        Food__c food = new Food__c(Quantity__c=2, Price__c=5,Lunch__c='Burger');
        insert food;
        food = [SELECT Total_Price__c FROM Food__c WHERE Id = :food.Id];
        System.assertEquals(10, food.Total_Price__c);
        
    }
    @isTest
    static void pizzaTest() {
        Food__c food = new Food__c(Quantity__c=2, Price__c=5,Lunch__c='Pizza');
        insert food;
        food = [SELECT Total_Price__c FROM Food__c WHERE Id = :food.Id];
        System.assertEquals(20, food.Total_Price__c);
        
    }
}