force-app/main/default/objects/Epam__c/Epam__c.object-meta.xml
<CustomObject>
    <label>Epam</label>
    <nameField>
        <displayFormat>v-{00000}</displayFormat>
        <label>Epam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Epam</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Epam__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Burger</fullName>
            </value>
            <value>
                <fullName>Pizza</fullName>
            </value>
            <value>
                <fullName>Kebab</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Epam__c/fields/Qty__c.field-meta.xml
<CustomField>
    <fullName>Qty__c</fullName>
    <label>Qty</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Epam__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/trgEPAM_Test.cls
@isTest
public class trgEPAM_Test {
         @isTest static void Test1Test()
    {
        EPAM__c t3 = new EPAM__c();
        t3.Product__c = 'Burger';
        t3.Rate__c = 2.99;
        t3.Qty__c = 3;
        
        Insert t3;
        
        List<EPAM__c> b = New List<EPAM__c>([select id,price__c from EPAM__c where id =: t3.id]);
    	
        // Now Calculate Price and assert expected Value
        System.assertEquals(8.97, b[0].price__c,'Price not Calculated Correctly');
        
    }

}