force-app/main/default/objects/RemoteSite__c/RemoteSite__c.object-meta.xml
<CustomObject>
    <label>RemoteSite</label>
    <nameField>
        <displayFormat>RS-{0000000}</displayFormat>
        <label>RemoteSite Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RemoteSite</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RemoteSite__c/fields/SiteName__c.field-meta.xml
<CustomField>
    <fullName>SiteName__c</fullName>
    <label>SiteName</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RemoteSite__c/fields/SiteURL__c.field-meta.xml
<CustomField>
    <fullName>SiteURL__c</fullName>
    <label>SiteURL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/RemoteSiteHelperTest.cls
@IsTest
private class RemoteSiteHelperTest 
{
    @IsTest
    private static void testCheckMetadataAPIConnection()
    {   
		remotesite__c myrs = new     remotesite__c();
        myrs.siteurl__c='www.test1.com';
        myrs.sitename__c='test1';
        myrs.description__c='test1';
        insert myrs;
        
        // Metadata API web Service mock implementation for tests
        Test.setMock(WebServiceMock.class, new WebServiceMockImpl());
        
        RemoteSiteHelperController controller = new RemoteSiteHelperController();
        System.assertEquals(true, controller.MetadataConnectionWarning);        
        controller.MetadataResponse = '';
        controller.displayMetadataResponse();
        System.assertEquals(false, controller.MetadataConnectionWarning);
        controller.MetadataResponse = 'Some Error Creating Remote Site Setting';
        controller.displayMetadataResponse();
        System.assertEquals(true, controller.MetadataConnectionWarning);
        
        myrs.siteurl__c='www.test2.com';
        myrs.sitename__c='test2';
        myrs.description__c='test2';  
        
        controller.save();
    }
    
    /**
     * Metadata API web service mock class for tests above
     **/
    private class WebServiceMockImpl implements WebServiceMock 
    {
        public void doInvoke(
            Object stub, Object request, Map<String, Object> response,
            String endpoint, String soapAction, String requestName,
            String responseNS, String responseName, String responseType) 
        {
            throw new TestException();
        }
    }
    
    public class TestException extends Exception { }
}